---

 - name: include vars
   include_vars:
     file: group_vars/secret_values
 
 - name: enable kv-v1 secret engine
   hashivault_secret_engine:
     name: kv
     url: "http://{{ inventory_hostname }}:8200"
     state: enabled
     authtype: token
     token: "{{ root_token }}"
     verify: no
   run_once: yes

 - name: write consul gossip encryption key to vault
   hashivault_secret:
     secret: "consul/config/encryption"
     data:
       key: "{{ encryption_key.stdout }}"
       ttl: "{{ consul_template_gossip_key_ttl }}"
     url: "http://{{ inventory_hostname }}:8200"
     mount_point: "kv"
     authtype: token
     token: "{{ root_token }}"
     verify: no
     version: 1
   run_once: yes

 - name: write nomad gossip encryption key to vault
   hashivault_secret:
     secret: "nomad/config/encryption"
     data:
       key: "{{ nomad_encryption_key.stdout }}"
       ttl: "{{ consul_template_gossip_key_ttl }}"
     url: "http://{{ inventory_hostname }}:8200"
     mount_point: "kv"
     authtype: token
     token: "{{ root_token }}"
     verify: no
     version: 1
   run_once: yes
