---

  - name: get consul-template checksums
    uri:
      url: "{{ hashicorp_url }}/{{ consul_template_uri }}/{{ consul_template_version }}/consul-template_{{ consul_template_version }}_SHA256SUMS"
      return_content: true
    become: true
    register: checksums

  - name: download consul-template binary
    get_url:
      url: "{{ hashicorp_url }}/{{ consul_template_uri }}/{{ consul_template_version }}/consul-template_{{ consul_template_version }}_linux_arm.zip"
      dest: "/opt/consul-template.zip"
      checksum: "sha256:{{ item.split(' ').0 }}"
      mode: 0777
    when: item is search("arm.zip")
    with_items: "{{ checksums.content.split('\n') }}"
    become: yes

  - name: unzip consul-template library
    unarchive:
      src: "/opt/consul-template.zip"
      dest: /usr/bin
      remote_src: yes
    become: yes

  - name: Create job
    community.general.nomad_job:
      host: localhost
      state: present
      content: "{{ lookup('template', 'consul_template_job.hcl.j2') }}"
      timeout: 120
      use_ssl: no
    run_once: true

